export const FETCH_PEERS = "FETCH_PEERS";
export const FETCH_PEERS_SUCCESS = "FETCH_PEERS_SUCCESS";
export const SHOW_SCREEN = "SHOW_SCREEN";
export const SHOW_DIALOG_COMPONENT = "SHOW_DIALOG_COMPONENT";
export const HIDE_DIALOG = "HIDE_DIALOG";
